<?php

namespace App\HttpController;

use EasySwoole\Component\Timer;
use EasySwoole\EasySwoole\Crontab\AbstractCronTask;
use EasySwoole\EasySwoole\Config;
use EasySwoole\EasySwoole\Swoole\Task\TaskManager;

use App\Tasks\TestTask;
use App\Models\Model;

class Index extends Base
{

    function task()
    {
        // TODO: Implement index() method.
        /*$taskClass = new TestTask();
        \EasySwoole\EasySwoole\Swoole\Task\TaskManager::async($taskClass);
        $this->response()->write('执行模板异步任务成功');*/
        /*TaskManager::async(function () {
            file_put_contents('./aaa.log',microtime(true));
        });*/

        // 每隔 10 秒执行一次
        /*Timer::getInstance()->loop(10 * 1000, function () {
            file_put_contents('./aaa.log', microtime(true) . PHP_EOL, FILE_APPEND);
        });*/
    }

    // 进入action之前的校验阶段
    public function onRequest(?string $action): ?bool
    {
        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }

    // action执行完毕后，会走到这里
    public function afterAction(?string $actionName): void
    {
        parent::afterAction($actionName); // TODO: Change the autogenerated stub
    }
}